"""Add email column to Booking

Revision ID: 886168c5eb4f
Revises: ca6ad387c38e
Create Date: 2025-05-03 12:42:22.080061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '886168c5eb4f'
down_revision = 'ca6ad387c38e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_column('email')

    # ### end Alembic commands ###
